language: julia
julia:
  - nightly
  - 1.1
  - 1.0.3os:
  - linux
  - osx
codecov: true
coveralls: true
notifications:
  email: false
matrix:
 allow_failures:
 - julia: nightly
git:
  depth: 99999999
#jobs:
#  include:
#    - stage: "Documentation"
#      julia: 1.1
#      os: linux
#      script:
#        - julia --project=test/ -e 'using Pkg; Pkg.add("Zygote"); Pkg.develop(PackageSpec(path=pwd()));Pkg.instantiate()'
#        - julia -e 'using Pkg; Pkg.activate(pwd()); Pkg.instantiate(); Pkg.build("YourPackage"); Pkg.test("YourPackage")'
#        - julia --project=test/ test/test.jl deploy
#      after_success: skip

after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'